const games = [
    'Flappy Bird',
    'Pac-Man',
    'Chess',
    '2048',
    'Dinosaur Game',
    'Agar.io',
    'Slither.io',
    'Cookie Clicker',
    'Fireboy and Watergirl',
    'Geometry Dash',
    'Super Smash Flash',
    'Pong',
    'Spaceman',
    'Happy Wheels',
    'Stickman Hook',
    'Pixel Speedrun',
    'Subway Surfers',
    // Add more games as needed
];